In [1]:
import torch
import torchvision
import torchvision.transforms as transforms
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
from torchsummary import summary
import torch.nn.init as init


In [2]:
x = torch.rand(2,2,2)
print(x)

tensor([[[0.9246, 0.9289],
         [0.1810, 0.7912]],

        [[0.4029, 0.2421],
         [0.6667, 0.1659]]])


In [3]:
x = torch.rand(2,2,2)
catted = torch.cat((x,x))
print(catted)


tensor([[[0.5116, 0.7084],
         [0.2928, 0.9248]],

        [[0.2049, 0.3851],
         [0.9366, 0.3499]],

        [[0.5116, 0.7084],
         [0.2928, 0.9248]],

        [[0.2049, 0.3851],
         [0.9366, 0.3499]]])


In [5]:
x = torch.rand(2,2,2)
catted = torch.cat((catted,x,catted))
print(catted)



tensor([[[0.5116, 0.7084],
         [0.2928, 0.9248]],

        [[0.2049, 0.3851],
         [0.9366, 0.3499]],

        [[0.5116, 0.7084],
         [0.2928, 0.9248]],

        [[0.2049, 0.3851],
         [0.9366, 0.3499]],

        [[0.7199, 0.9094],
         [0.9757, 0.6307]],

        [[0.9154, 0.0146],
         [0.6612, 0.8982]],

        [[0.1282, 0.8788],
         [0.0161, 0.5890]],

        [[0.2610, 0.2885],
         [0.5123, 0.0279]],

        [[0.5116, 0.7084],
         [0.2928, 0.9248]],

        [[0.2049, 0.3851],
         [0.9366, 0.3499]],

        [[0.5116, 0.7084],
         [0.2928, 0.9248]],

        [[0.2049, 0.3851],
         [0.9366, 0.3499]],

        [[0.7199, 0.9094],
         [0.9757, 0.6307]],

        [[0.9154, 0.0146],
         [0.6612, 0.8982]]])
