In [1]:
from __future__ import print_function
import torch

초기화되지 않은 5x3 행렬을 생성합니다:

In [2]:
x = torch.empty(5, 3)
print(x)

tensor([[-3.0933e+24,  4.5864e-41, -3.0934e+24],
        [ 4.5864e-41, -3.0934e+24,  4.5864e-41],
        [-3.0944e+24,  4.5864e-41, -3.0934e+24],
        [ 4.5864e-41, -3.0945e+24,  4.5864e-41],
        [-3.0945e+24,  4.5864e-41, -3.0945e+24]])


In [3]:
x = torch.rand(5, 3)
print(x)

tensor([[0.6878, 0.3812, 0.7786],
        [0.8283, 0.6850, 0.6007],
        [0.4830, 0.7040, 0.7062],
        [0.7800, 0.0876, 0.4040],
        [0.7825, 0.7607, 0.6989]])


In [4]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)


tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [5]:
x = torch.zeros(5, 3, dtype=torch.short)
print(x)


tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]], dtype=torch.int16)


In [6]:
x = torch.zeros(5, 3, dtype=torch.fp16)
print(x)


AttributeError: module 'torch' has no attribute 'fp16'

In [7]:
x = torch.zeros(5, 3, dtype=torch.float16)
print(x)


tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]], dtype=torch.float16)


In [11]:
x = torch.tensor([[3.5, 2.5],[1.5, 0.5]])
print(x)

tensor([[3.5000, 2.5000],
        [1.5000, 0.5000]])


In [12]:
print(x.size())

torch.Size([2, 2])


In [13]:
y = torch.rand(5,3)
x = torch.rand(5,3)
print(x+y)

tensor([[0.9375, 0.0751, 0.6837],
        [0.7511, 0.6428, 1.3296],
        [0.2643, 1.2894, 0.6217],
        [1.0203, 1.1223, 0.4953],
        [1.1653, 1.5287, 1.2982]])


In [ ]:
result = torch.empty(5,3)

