In [1]:
from __future__ import print_function
import torch
x = torch.rand(5, 3)
print(x)


tensor([[0.1407, 0.2064, 0.2064],
        [0.1942, 0.6714, 0.4130],
        [0.2812, 0.9123, 0.9374],
        [0.0276, 0.9923, 0.2016],
        [0.7406, 0.3061, 0.0611]])


In [2]:
torch.cuda.is_available()

True

torch 사이즈 구하기

In [3]:
print(x.size())

torch.Size([5, 3])


In [5]:
y = torch.rand(5, 3)
print(x + y)

tensor([[0.7121, 0.5990, 0.5021],
        [0.2942, 1.0363, 0.4446],
        [1.2797, 1.3710, 1.6883],
        [0.6574, 1.8588, 1.1922],
        [1.5412, 0.4264, 0.1198]])


In [6]:
result = torch.Tensor(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[0.7121, 0.5990, 0.5021],
        [0.2942, 1.0363, 0.4446],
        [1.2797, 1.3710, 1.6883],
        [0.6574, 1.8588, 1.1922],
        [1.5412, 0.4264, 0.1198]])


cuda 를 이용해서 계산하기

In [9]:
if torch.cuda.is_available():
    x = x.cuda()
    y = y.cuda()
print(x + y)

tensor([[0.7121, 0.5990, 0.5021],
        [0.2942, 1.0363, 0.4446],
        [1.2797, 1.3710, 1.6883],
        [0.6574, 1.8588, 1.1922],
        [1.5412, 0.4264, 0.1198]], device='cuda:0')


In [13]:
from apex import amp
N, D_in, D_out = 64, 1024, 512
x = torch.randn(N, D_in, device="cuda")
y = torch.randn(N, D_out, device="cuda")

model = torch.nn.Linear(D_in, D_out).cuda()
optimizer = torch.optim.SGD(model.parameters(), lr=1e-3)
model, optimizer = amp.initialize(model, optimizer, opt_level="O1")
for to in range(500): 
    y_pred = model(x)
    loss = torch.nn.functional.mse_loss(y_pred, y)
    print(loss)
    optimizer.zero_grad()
    with amp.scale_loss(loss, optimizer) as scaled_loss: 
        scaled_loss.backward()
    optimizer.step()


Selected optimization level O1:  Insert automatic casts around Pytorch functions and Tensor methods.

Defaults for this optimization level are:
enabled                : True
opt_level              : O1
cast_model_type        : None
patch_torch_functions  : True
keep_batchnorm_fp32    : None
master_weights         : None
loss_scale             : dynamic
Processing user overrides (additional kwargs that are not None)...
After processing overrides, optimization options are:
enabled                : True
opt_level              : O1
cast_model_type        : None
patch_torch_functions  : True
keep_batchnorm_fp32    : None
master_weights         : None
loss_scale             : dynamic
tensor(1.3462, device='cuda:0', grad_fn=<MseLossBackward>)
tensor(1.3461, device='cuda:0', grad_fn=<MseLossBackward>)
tensor(1.3459, device='cuda:0', grad_fn=<MseLossBackward>)
tensor(1.3457, device='cuda:0', grad_fn=<MseLossBackward>)
tensor(1.3455, device='cuda:0', grad_fn=<MseLossBackward>)
tensor(1.3454, dev

tensor(1.3141, device='cuda:0', grad_fn=<MseLossBackward>)
tensor(1.3140, device='cuda:0', grad_fn=<MseLossBackward>)
tensor(1.3138, device='cuda:0', grad_fn=<MseLossBackward>)
tensor(1.3136, device='cuda:0', grad_fn=<MseLossBackward>)
tensor(1.3135, device='cuda:0', grad_fn=<MseLossBackward>)
tensor(1.3133, device='cuda:0', grad_fn=<MseLossBackward>)
tensor(1.3131, device='cuda:0', grad_fn=<MseLossBackward>)
tensor(1.3130, device='cuda:0', grad_fn=<MseLossBackward>)
tensor(1.3128, device='cuda:0', grad_fn=<MseLossBackward>)
tensor(1.3126, device='cuda:0', grad_fn=<MseLossBackward>)
tensor(1.3125, device='cuda:0', grad_fn=<MseLossBackward>)
tensor(1.3123, device='cuda:0', grad_fn=<MseLossBackward>)
tensor(1.3121, device='cuda:0', grad_fn=<MseLossBackward>)
tensor(1.3120, device='cuda:0', grad_fn=<MseLossBackward>)
tensor(1.3118, device='cuda:0', grad_fn=<MseLossBackward>)
tensor(1.3116, device='cuda:0', grad_fn=<MseLossBackward>)
tensor(1.3115, device='cuda:0', grad_fn=<MseLossBackward

tensor(1.2806, device='cuda:0', grad_fn=<MseLossBackward>)
tensor(1.2804, device='cuda:0', grad_fn=<MseLossBackward>)
tensor(1.2803, device='cuda:0', grad_fn=<MseLossBackward>)
tensor(1.2801, device='cuda:0', grad_fn=<MseLossBackward>)
tensor(1.2799, device='cuda:0', grad_fn=<MseLossBackward>)
tensor(1.2798, device='cuda:0', grad_fn=<MseLossBackward>)
tensor(1.2796, device='cuda:0', grad_fn=<MseLossBackward>)
tensor(1.2795, device='cuda:0', grad_fn=<MseLossBackward>)
tensor(1.2793, device='cuda:0', grad_fn=<MseLossBackward>)
tensor(1.2791, device='cuda:0', grad_fn=<MseLossBackward>)
tensor(1.2790, device='cuda:0', grad_fn=<MseLossBackward>)
tensor(1.2788, device='cuda:0', grad_fn=<MseLossBackward>)
tensor(1.2786, device='cuda:0', grad_fn=<MseLossBackward>)
tensor(1.2785, device='cuda:0', grad_fn=<MseLossBackward>)
tensor(1.2783, device='cuda:0', grad_fn=<MseLossBackward>)
tensor(1.2782, device='cuda:0', grad_fn=<MseLossBackward>)
tensor(1.2780, device='cuda:0', grad_fn=<MseLossBackward